### ISSUE TITLE
An 'alias' feature to help deprecate parameters more easily

### ISSUE THREAD

**Issue by jlstevens** [holoviz/param#112]
It would be nice to have a way of gradually deprecating parameters or at least changing their names as necessary. The suggestions is to have an 'alias' argument to any `Parameter`:

``` python
class Foo(param.Parameterized):

  foo = param.String(default='Some string', alias=['bar', 'baz'])
```

Then when the `Parameterized` class is constructed, we know that any access to 'bar' and 'baz' are aliased to the 'foo' `Parameter`.

This system means that when a declared alias is used (or at least the first time it is used) , we can then inform the user with 1) nothing at all  2) deprecation warnings 3) exceptions. This deprecation path would help smooth out the process of making minor API changes (i.e. renaming parameters over time), at least from the perspective of the user.

**Comment by jbednar** [comment]
This would be very useful.

**Comment by jlstevens** [comment]
Agreed but I don't think it will get done for the update param release later today!

**Comment by ceball** [comment]
See also #174

**Comment by jbednar** [comment]
Closing due to lack of interest in implementing this feature, but it does seem like it would be useful if someone wants to implement it with appropriate support for deprecation messaging, etc.

**Comment by ceball** [comment]
@jbednar I'm not clear on what the criteria for "wishlist" are. This seems like a reasonable feature request, but not one any of us is planning to implement any time soon. E.g. why categorize this issue differently from #249?

Can we add this kind of thing to a "wishlist" tag or milestone, where the "wishlist" is a collection of closed but not actually "fixed"/"done" issues. Closed so they don't interfere with people's sanity trying to triage etc (the reason for closing this?). But still easy to find if interested. If an item gets done, the "wishlist" tag/milestone would be removed. (This is different from how wishlist is being used currently, I think.)

If "wishlist" is already be being used across projects to mean something else, then the name could be different. "Ideas" or "Proposals" or "Discussions" or something like that?

Just seems a shame not to record relatively concrete proposals/requests that experienced people (e.g. Jean-Luc in this case) might have - someone looking for a fun/"not critical path" project might want to try one of them.

**Comment by ceball** [comment]
Maybe all I need to do is remove "actually done" items from the wishlist (https://github.com/holoviz/param/milestone/2), and meanwhile you are gradually/in the process of closing items on the wishlist if they are not likely to be worked on soon, at which point the wishlist would be what I (think I) want - a list of proposals/requests that nobody's planning to work on any time soon (and which don't interfere with use of the issue tracker by showing up as open).

**Comment by jbednar** [comment]
> @jbednar I'm not clear on what the criteria for "wishlist" are. This seems like a reasonable feature request, but not one any of us is planning to implement any time soon. E.g. why categorize this issue differently from #249?

"a reasonable feature request, but not one any of us is planning to implement any time soon" is indeed the criterion for being on the wishlist, so in that sense it is categorized the same as #249; both are on the wishlist.  For triaging, it doesn't matter if an issue is open or closed; triaging is considered done if the issue has been placed on any milestone, including wishlist.  So triaging should only ever consider issues that aren't on a milestone, and then releases focus on whatever is on that release's milestone. 

Here it's a valid wishlist item, but because the only people I can ever imagine implementing it have failed to do so for too long, I closed it because it's a bit distracting from other wishlist items that are much more likely to happen.  That's a judgment call, but since both open and closed issues live forever, it doesn't seem like the stakes are high if someone disagrees with that judgement.  

Meanwhile, removing actually done items from the wishlist would be great, removing the wishlist tag and if appropriate replacing that tag with the milestone for the release in which it was done (a very optional nicety).

**Comment by jbednar** [comment]
I guess what you're suggesting/observing is that the "wishlist" milestone has or should have a special status. For a regular milestone, tagging that milestone in the issue means that it's a to-do item for that release (if open) or that it was done for that release (if closed). Because "wishlist" will never be released, there's no meaning of "done in the wishlist release" for a closed item, so we could repurpose "closed but on the wishlist" to mean "on the wishlist, not done, but also seems unlikely to be done or unlikely to be as high in priority as those that are on the wishlist but open".  That sounds reasonable to me, and indeed would help keep the number of open issues more manageable...

**Comment by ceball** [comment]
That sounds good, hopefully keeping active maintainers happy.

**Comment by jbednar** [comment]
Ok, I've updated our [HoloViz triaging guidelines](https://hackmd.io/dgLSCjkhQVKmjzj9kKl-sA?view) to reflect that:

![image](https://user-images.githubusercontent.com/1695496/93355643-e80d5680-f803-11ea-9f75-76efb07eb615.png)
