### ISSUE TITLE
Warnings do not display in notebooks for certain ipykernel versions

### ISSUE THREAD

**Issue by jlstevens** [holoviz/param#133]
This issue is simply to note that a bug in certain older ipykernel versions meant parameterized warnings were not appearing in notebooks. 

I believe this issue was fixed in ipython/ipykernel#127 which should means that this issue was fixed for ipykernel version 4.4. This is consistent with what I experienced: when I had version 4.3.1, warnings only appeared in the terminal but after updating to the latest version (4.5.0), the issue was resolved.

**Comment by ceball** [comment]
I found the same thing recently.

I'm using continuumio/anaconda3:4.1.1 from dockerhub, and had a tough time upgrading ipykernel. (I think because of problem with conda, but I'm not at all sure; https://github.com/ContinuumIO/anaconda-issues/issues/542.) Here's what I did:

```
pip install --upgrade --ignore-installed https://github.com/ipython/ipykernel/tarball/master
```

Maybe you didn't have any trouble upgrading ipykernel, Jean-Luc?

I'll also just note that when I import param in a notebook, I get a deprecation warning:
```
/opt/conda/lib/python3.5/site-packages/ipykernel/__main__.py:1: DeprecationWarning: Use importlib.util.find_spec() instead.
  if __name__ == '__main__':
```

Presumably that's because I'm using python 3.5, and it's something ipykernel needs to address. Annoying to get it when I import param, though.

**Comment by ceball** [comment]
Check if this is still a problem

**Comment by jlstevens** [comment]
I *believe* this is no longer a problem with recent versions. I might be wrong though!

**Comment by ceball** [comment]
See also #68 if checking/cleaning up

**Comment by jbednar** [comment]
Appears not to be an issue any more.
