### ISSUE TITLE
Use __signature__ to generate Parameterized signatures

### ISSUE THREAD

**Issue by philippjfr** [holoviz/param#371]
Currently we use a docstring trick to generate signatures for Parameterized classes. This approach is no longer supported by IPython in recent versions and is also pretty hacky (and ugly to look at in a docstring since all the keywords appear there). Instead we should use the ``__signature__`` object (see [PEP362](https://www.python.org/dev/peps/pep-0362/)).

![Screen Shot 2020-01-18 at 9 51 33 PM](https://user-images.githubusercontent.com/1550771/72670351-b8236e80-3a3c-11ea-87a9-1077571a698a.png)

**Comment by philippjfr** [comment]
Since this may not be desirable for all Parameterized classes another suggestion might be that you can turn this one for certain Parameter classes by setting some flag on the class, e.g. `Parameterized._expand_signature = True`.

**Comment by jlstevens** [comment]
The above screenshot is based on a holoviews example (``opts``) but there is an issue when generalized to all the things param supports. The problem is that ``__signature__`` is used for inspection (as described in the PEP above) so it will be relied on by anything doing inspection (as opposed to just being helpful for tab-completion).

The issue then is that we would like to support tab-completion for parameterized classes (i.e constructors) as well as for parameterized functions. The ```__signature__``` should then reflect reality i.e including any positional arguments, `*args` and ``**kwargs`` that don't correspond to parameters.

The problem with say expanding ``**kwargs`` into a list of explicit parameter keywords followed by ``**kwargs`` is that this makes assumptions about how param is being used:

* The ``**kwargs`` in the constructor may be filtered/processed before mapping them to the parameters. For instance, nothing stops you from declaring a class with parameter `foo` that does not accept `foo` as a keyword in the constructor.

* You would always need to allow for ``**kwargs`` even when the entire set of keywords *are* parameters - you have no way of knowing whether kwargs that aren't parameters are being used or not.

* Things can get even messier with parameterized functions (i.e many instance of ``__call__`` won't use ``ParamOverrides``).

While I do think the docstring approach was ugly and hacky, it had the nice property of only really being a hint for tab-completion. Setting ``__signature__`` is a more serious affair (assuming you don't want to mess around with the results of inspection) so while I prefer this approach, I think it is important to specify signatures that don't deviate too much from what is actually accepted by the constructors/``__call__`` methods.

**Comment by jlstevens** [comment]
> Since this may not be desirable for all Parameterized classes another suggestion might be that you can turn this one for certain Parameter classes by setting some flag on the class, e.g. Parameterized._expand_signature = True.

Not a bad suggestion! 

Any such flag when disabled, should not mess with ``__signature__`` at all.  As a consequence, I think it should be called something like ``Parameterized._set_expanded_signature=True`` to be completely explicit. The other version allows for the possibility that ``__signature__`` is still set, just without expanded ``**kwargs`` (which would be a little strange to do but valid).

**Comment by philippjfr** [comment]
>While I do think the docstring approach was ugly and hacky, it had the nice property of only really being a hint for tab-completion.

The main problem with it is unfortunately not that it is hacky but that it is [no longer supported](https://github.com/ipython/ipython/issues/11561), so we should find some way to replace it. I agree with all the issues you raised though so what I think I would like to see is find some approach that:

* Allows you to enable/disable it for specific classes and their subclasses
* Allows customizing it in some form, e.g. allowing you to declare parameters that should not be listed

**Comment by jlstevens** [comment]
Agreed with those two points. I would like to add another two:

* I am tempted to say that tab-completion should be made *possible* with param but maybe not necessarily on by default (as it may not get ```__signature__``` quite right).
* But if someone wants help tab-completing parameters, it should be as easy as possible to enable for chosen classes.

**Comment by jlstevens** [comment]
For instance, instead of asking users to set ``Foo.__init__.__signature__`` I can imagine a utility that might roughly work as:

```python
param.set_signatures(Foo, Bar, Baz, **kwargs)
```

Where the ``**kwargs`` to the utility are flexible enough to make sure the signatures are correct. For instance you might have `ignore` with a list of parameter names that should not be allowed as kwargs, some option to specify parameters set as positional arguments, additional named positional arguments, whether ``**kwargs`` should be specified given the parameters are listed etc etc.

**Comment by maximlt** [comment]
As I had a look at this issue due to https://github.com/holoviz/param/issues/785, I'll just note that we should definitely look into how `dataclasses`/`attrs`/`pydantic` handle this sort of thing
