### ISSUE TITLE
ClassSelector and instantiate does not work as expected

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/param#406]
#### My Pain

I'm trying to create v2 of awesome-panel.org. I'm creating a bunch of *services* that are shared by instantiating them once (Pythons version of dependency injection I believe).

So my components will be using those services by default. But I thought why not enable my components to watch/ subscribe to other services?

But it did not work at at first as I was surprised how the `instantiate` of `param.ClassSelector` works.

I've been trying to understand how `instantiate` works for a long time. But I've not been able to find it documented or been able to understand it from the source code yet.

#### Code Example

```python
import param

class ProgressService(param.Parameterized):
    value = param.Integer()

progress_service = ProgressService()
print(progress_service.name)

class ProgressComponent(param.Parameterized):
    progress_service = param.ClassSelector(default=progress_service, class_=ProgressService)

progress_component = ProgressComponent()

print(progress_component.progress_service.name)
assert progress_component.progress_service == progress_service
```

```bash
$ python 'scripts\issue_class_selector.py'
ProgressService00002
ProgressService00004
Traceback (most recent call last):
  File "scripts\issue_class_selector.py", line 15, in <module>
    assert progress_component.progress_service == progress_service
AssertionError
```

**I would have expected no AssertionError**. I provide an instance and I would not have expected another instance to be constructured. 

- Why does it do that?
      - Why would someone want to instantiate a new version of an instance by default?
- Is that expected?

#### Solution

Either 

- explain the why, what and how of `instantiate` or 
- document the why, what and how of `instantiate` or
- if this is a bug then fix.

#### Additional Context

If I set `instantiate` to `False` it works as expected.

```python
import param

class ProgressService(param.Parameterized):
    value = param.Integer()

progress_service = ProgressService()
print(progress_service.name)

class ProgressComponent(param.Parameterized):
    progress_service = param.ClassSelector(default=progress_service, class_=ProgressService, instantiate=False)

progress_component = ProgressComponent()

print(progress_component.progress_service.name)
assert progress_component.progress_service == progress_service
```

```bash
$ python 'scripts\issue_class_selector.py'
ProgressService00002
ProgressService00002
(.venv)
```

**Comment by MarcSkovMadsen** [comment]
#### Additional Context

One of the things that keeps confusing me about `instantiate` is this example

```python
import param

class Theme(param.Parameterized):
    pass

class ProgressSpinner(param.Parameterized):
    theme = param.ClassSelector(class_=Theme, instantiate=True)

progress_spinner = ProgressSpinner()
assert isinstance(progress_spinner.theme, Theme)
```
```bash
$ python 'scripts\issue_class_selector.py'
Traceback (most recent call last):
  File "scripts\issue_class_selector.py", line 10, in <module>
    assert isinstance(progress_spinner.theme, Theme)
AssertionError
```

I would have expected no AssertionError

And the problem is I would often like to construct the ClassSelector value on instantiation of the Parameterized Class. Currently I do this by overriding the `__init__` but I would wish there was a more clean version (i.e. by configuration) of that. I believe that would be more natural to a lot of users.

**Comment by jbednar** [comment]
Sorry for the confusing docs! We've recently gotten funding to write a proper user manual for Param sometime in 2020, but we haven't started that project yet. In the meantime, there are probably a few things I can explain. `instantiate` is meant to determine whether a parameter's value should be shared across multiple instances of that class or any of its subclasses. I.e., when you instantiate a Parameterized object, should that Parameter's value also be instantiated, or should it instead inherit its value from the class or whatever superclass defined that default value? If `instantiate==True`, that parameter value is copied into each Parameterized object when the Parameterized object is instantiated. If `instantiate=False`, the default value that was set at the class level is returned whenever that Parameter is looked up, whether on that class, a subclass, or an instance of that class or any of its subclasses, unless the default has been changed to a specic value somewhere along that chain of inheritance. `instantiate=False` provides the user a lot of power to control whole sets of instantiated objects (and entire class hierarchies) by changing the default default at a superclass level, with that value then affecting all those classes and objects. With `instantiate=True`, if you wanted to change such a setting, you'd have to find every subclass and every instantiated object to change the value.  So `instantiate=False` provides a lot of power to the end user.

So, why would anyone want `instantiate=True`? Well, what if your parameter's value `v` is itself mutable?  If `instantiate=False` in that case, if you look up the value of some parameter on some object or on some subclass, then change something internal to `v`, it will immediately affect that parameter value on the superclass, on other instantiated objects, and on other subclasses. Such behavior can be very confusing unless you realize that it's happening. If the Parameter is an ObjectSelector, choosing between a list of a few heavyweight objects that the user already knows about and expects to be global, then such behavior is fine -- the user then expects to be working with that specific named object no matter what parameter on what class it might be showing up in. So again in that specific case, `instantiate=False` is fine, which is why `instantiate=False` for an ObjectSelector.

But in the case where a parameter value is mutable and each instantiated Parameterized object should have its own copy owned just by it, you should use `instantiate=True`. Or if you want to "capture" the class value at instantiation time, so that an instance has the value that Parameter had when it was created, independently of any subsequent change by the user at the class level, again, you should use `instantiate=True`.  With `instantiate==True`, the parameter value will be "filled in" whenever that Parameterized class is instantiated, and will then be fully independent (for good and bad) of all superclasses, subclasses, and other instantiated objects.  

A ClassSelector confusingly has two very different usages, either to select a class itself (presumably to be instantiated by user code), or to accept an object of a specified class. Those probably should have been two different Parameters, but that behavior was chosen many years ago, and too late to change now.  In the case of selecting a class, instantiating is irrelevant.  In the case of selecting an object, the idea is that this Parameter is selecting any object of the appropriate class, not just one of a pre-defined list of instantiated ones, and so `instantiate==True` by default to avoid the confusing "aliasing" issues you'd otherwise have for mutable parameter values shared between instances and between subclasses.

I'm not sure if I addressed everything you're asking, but hopefully it helps?

**Comment by MarcSkovMadsen** [comment]
Thanks @jbednar 

I think the comes from me interpreting "instantiate" differently.

I thought I could provide a class as default value and then `instantiate` would determine whether to instantiate the default value or not when instantiating the parameterized class. That feature I've looking for lots of times.

**Comment by jbednar** [comment]
I'm not sure how that would work, as instantiating a class normally requires passing in arguments to a constructor. It could be instantiated with only the default arguments, but that seems limited, so I think we'd have to have some way to have a user-settable list of arguments to use for construction.  Seems tricky!

Moreover, accepting a class but returning an instance would also violate Param's design where the default value, the value a user sets with an assignment, and the value a user reads out with attribute access are all one and the same type and identity of object.  E.g. `class A(Parameterized): x=param.Int(default=3)`, `A.x=3`, and `print A.x` (returning 3) are all the same type and id (integer and "3").  As you are proposing it seems like the `default` would be of type "class" and setting `a.x` would require a class, but reading out `A.x` (or at least `a.x`, where `a` is an instance of `A`) would return an instance (not a class)?  Seems very confusing and very unlike any other Parameter! I hope we can figure out a better solution for what you are trying to do.
