### ISSUE TITLE
Make crop_to_bounds work on dates

### ISSUE THREAD

**Issue by dabbatelli** [holoviz/param#416]
As stated in the title, crop_to_bounds does not work for non-numeric parameters such as `param.Date`, returning the default value instead of the cropped value as the name would suggest:

``` python
import param
from datetime import datetime

_DATE_BOUNDS = (datetime(2010, 1, 1).date(), datetime(2030, 1, 1).date())
d = param.Date(bounds=_DATE_BOUNDS)

d.crop_to_bounds(datetime(2020, 1, 10).date()) # Returns None
```

While this behavior is described in the crop_to_bounds docstring, it kind of defeats the purpose of having the function available  on Date parameters in the first place.
The fact that crop_to_bounds accepts all values without returning an error has the potential to cause some hard-to-debug bugs for those who don't carefully read the docstring.

**Comment by jbednar** [comment]
I don't think the behavior for dates was intentional; this is a method on Number and the check for `_is_number` was just meant to ensure that only suitable values are accepted (no strings, etc.), e.g. from a text input box.  At some point dates were added as a param.Number subtype, but no one noticed that `_is_number` is no longer appropriate. Because Number subtypes in general won't be able to handle dates, we probably can't safely make`_is_number` accept dates.  Instead we probably need to provide a specialized implementation of `crop_to_bounds` for param.Date and param.CalendarDate.  I _think_ this implementation should not just _accept_ dates, but should in fact _require_ dates. 

Would you be comfortable implementing that method, so that we can be sure it meets your needs?  I could write it easily but don't often use date parameters in my own work so I might not think of all the cases it should cover.

**Comment by dabbatelli** [comment]
> Would you be comfortable implementing that method, so that we can be sure it meets your needs? I could write it easily but don't often use date parameters in my own work so I might not think of all the cases it should cover.

To be honest I am not a programmer and I am still at my first experiences with Python and Param, but my implementation would look like this:

```python
    def crop_to_bounds(self,val):
        """
        Return the given value cropped to be within the hard bounds
        for this parameter.
        
        Accepts values of date or datetime type and None (if allow_None = True).
        
        In case of non-inclusive bounds, the value is cropped to the nearest
        time unit for the type used in the bounds (1 day in case of dates,
        1 microsecond in case of datetime types).
        """
        if self.allow_None and val is None:
            return
                 
        if self.bounds is None:
            return val
          
        if not isinstance(val, dt_types) and not (self.allow_None and val is None):
            raise ValueError("Date '%s' only takes datetime and date types."%self.name)   
  
        lbound, hbound = self.bounds
        incmin,incmax = self.inclusive_bounds
             
        if lbound is not None:
            if incmin == True:
                vmin = lbound
            else: 
                if isinstance(val, dt.datetime):
                    vmin = lbound + dt.timedelta(microseconds=1)
                else:
                    vmin = lbound + dt.timedelta(days=1)
            if val < vmin:
                return  vmin

        if hbound is not None:
            if incmax == True:
                vmax = hbound
            else:
                if isinstance(val, dt.datetime):
                    vmax = hbound - dt.timedelta(microseconds=1)
                else:
                    vmax = hbound - dt.timedelta(days=1)                      
            if val > vmax:
                return vmax
          
        return val
```

It became a bit longer than expected, but it does handle non-inclusive bounds with both date and datetime types.

The implementation could be a bit simpler for CalendarDate, which to my understanding only supposed to accept date types (not datetime), but it turns out it is possible to use datetime bounds in CalendarDate as well, so at this point I am not quite sure about the difference between Date and CalendarDate.

**Comment by tonyfast** [comment]
As far as we can tell, inappropriately inherited behaviour has recently been corrected. This seems like a reasonable, but not urgent.
