### ISSUE TITLE
docs not correctly rendered at https://param.holoviz.org/Reference_Manual/param.html

### ISSUE THREAD

**Issue by cjw296** [holoviz/param#481]
See https://param.holoviz.org/Reference_Manual/param.html.

Big bunch of text along the lines of:
```
digraph inheritance6ce4706456 { bgcolor=transparent; fontsize=18; rankdir=LR; size="12.0, 12.0"; "param.__init__.Action" [URL="#param.__init__.Action",fillcolor=white,fontname="Vera Sans, DejaVu Sans, Liberation Sans, Arial, Helvetica, sans",fontsize=10,height=0.25,shape=box,style="setlinewidth(0.5),filled",target="_top",tooltip="A user-provided function that can be invoked like a class or object method using ()."]; "param.__init__.Callable" -> "param.__init__.Action" [arrowsize=0.5,style="setlinewidth(0.5)"]; "param.__init__.Array" [URL="#param.__init__.Array",fillcolor=white,fontname="Vera Sans, DejaVu Sans, Liberation Sans, Arial, Helvetica, sans",fontsize=10,height=0.25,shape=box,style="setlinewidth(0.5),filled",target="_top",tooltip="Parameter whose value is a numpy array."]; "param.__init__.ClassSelector" -> "param.__init__.Array" [arrowsize=0.5,style="setlinewidth(0.5)"]; "param.__init__.Boolean" [URL="#param.__init__.Boolean",fillcolor=white,fontname="Vera Sans, DejaVu Sans, Liberation Sans, Arial, Helvetica, sans",fontsize=10,height=0.25,shape=box,style="setlinewidth(0.5),filled",target="_top",tooltip="Binary or tristate Boolean Parameter."]; "param.parameterized.Parameter" -> "param.__init__.Boolean" [arrowsize=0.5,style="setlinewidth(0.5)"]; "param.__init__.CalendarDate" [URL="#param.__init__.CalendarDate",fillcolor=white,fontname="Vera Sans, DejaVu Sans, Liberation Sans, Arial, Helvetica, sans",fontsize=10,height=0.25,shape=box,style="setlinewidth(0.5),filled",target="_top",tooltip="CalendarDate parameter of date type."]; "param.__init__.Number" -> "param.__init__.CalendarDate" [arrowsize=0.5,style="setlinewidth(0.5)"]; "param.__init__.CalendarDateRange" [URL="#param.__init__.CalendarDateRange",fillcolor=white,fontname="Vera Sans, DejaVu Sans, Liberation Sans, Arial, Helvetica, sans",fontsize=10,height=0.25,shape=box,style="setlinewidth(0.5),filled",target="_top",tooltip="A date range specified as (start_date, end_date)."]; "param.__init__.Range" -> "param.__init__.CalendarDateRange" [arrowsize=0.5,style="setlinewidth(0.5)"]; "param.__init__.Callable" [URL="#param.__init__.Callable",fillcolor=white,fontname="Vera Sans, DejaVu Sans, Liberation Sans, Arial, Helvetica, sans",fontsize=10,height=0.25,shape=box,style="setlinewidth(0.5),filled",target="_top",tooltip="Parameter holding a value that is a callable object, such as a function."]; "param.parameterized.Parameter" -> "param.__init__.Callable" [arrowsize=0.5,style="setlinewidth(0.5)"]; "param.__init__.ClassSelector" [URL="#param.__init__.ClassSelector",fillcolor=white,fontname="Vera Sans, DejaVu Sans, Liberation Sans, Arial, Helvetica,
...
```

...where I'm guessing more useful docs should be. In my case I'd trying to learn more about `depends` and `watch` but doesn't look like they're really documented anywhere?

**Comment by rithwikjc** [comment]
I also wanted to enquire about the documentation for this library. Is it just that no-one ever got around to writing documentation? I do not even understand the basics of params, like should I declare params as instance variables (inside `__init__`) or static variables in a class?

It is pretty well integrated with the `panels` library and how I started using parameters. However there is barely any documentation on the param. It not only is making it hard to use param, but also panel, which heavily uses param in most of its documentation. So far I have been shuttling back and forth between param and panel documentation to make sense of things, and panel's documentation does more for helping me use param than param's own documentation. I am considering ditching param and just using widgets in panel because of it.

**Comment by jbednar** [comment]
This issue is about the reference (API) manual, but I think your question is mainly about the woefully inadequate user guide. 
A new version of the Param user docs is in progress at https://pyviz-dev.github.io/param , but there are still many gaps.  I'd expect about two more weeks until that version becomes Param's main website, and I'm hoping that it will have much more content by then.  To answer your specific question, params are normally declared as static attributes of a Parameterized class.  Some bits work in other contexts, but as of now that's the only fully supported usage.

**Comment by jbednar** [comment]
Oh, and if you want to know why the docs are so bad, Param was developed inside a larger project (not Panel) in 2003, and was initially documented in that domain-specific project only.  We've all moved on from that project and already know Param deeply ourselves without needing any docs, and while people are funding lots of work based on Param almost no one is funding work on Param itself. We did have a bit of funding that led to the above draft site, but the rest is all whatever time we can scrape together after a long data programming and managing projects, so it gets shunted along.  But it's currently #2 in my list, after releasing Datashader hopefully this weekend!

**Comment by rithwikjc** [comment]
Thanks for taking the trouble to type these out and answering my question. 🙂 It's nice to know a little about the history of the project.
The new website looks great and it's great to see that documentation for this project is not abandoned. I will try to contribute to documentation if I am able to wrap my head around how to use param properly. 😄 

Being a project that's tightly integrated with other interesting projects like panel. I think it would really help improve the adoption of not just param, but all the other libraries that use param, if param were to have good documentation.

**Comment by jbednar** [comment]
The new reference manual (https://pyviz-dev.github.io/param/reference.html) no longer includes "digraph" in the output, so I think this is fixed. The new site should go live when Param 1.11.0 is released, which is imminent, so I will close this. Still need more docs for events and watchers, but that's noted in the user guide index, so we won't lose track of it.

**Comment by cjw296** [comment]
Nice, thanks!
