### ISSUE TITLE
Formatting string

### ISSUE THREAD

**Issue by ahuang11** [holoviz/param#506]
I really appreciate the docs for param.

Quick question about 
https://pyviz-dev.github.io/param/user_guide/Logging_and_Messages.html#writing-log-messages

"
You may wonder (a) why the formatting string is “old style” , and (b) why the formatting values “actual, desired” are not combined directly with the formatting string. I.e., why not just use a Python3 f-string, like:
"

Wanted to clarify, although no f-string, but is using `.format()` okay?

**Comment by ahuang11** [comment]
Probably not, now that I read the function signature.

**Comment by jbednar** [comment]
.format() is ok, but discouraged, because it is not lazy. Particularly for debug messages that might be deep in an inner loop, it can be very expensive to format a string that you aren't going to display. .format() will format the string, _then_ call the logging module, and for debugging messages the logging module is very likely to simply return immediately, having done no computation (assuming you are not in debug mode). So if you use .format or f-strings or any other non-lazy approach, your code can be drastically slower. If the logging module were written now, in 2021, I'm sure it would have lazy f-strings, but we're stuck with the only lazy option being % formatting, I'm afraid!  Feel free to expand my explanation of this in the docs (now up at param.holoviz.org) if you think more detail would be helpful!
