### ISSUE TITLE
Command line interface with param?

### ISSUE THREAD

**Issue by ahuang11** [holoviz/param#565]
Is this within scope of param, wrapper for argparse?

**Comment by jbednar** [comment]
Completely within the scope. We have had several partial versions of this over the years, none ever polished enough to include, but that's just because we've never had the time to focus on it and finish it! So yes, please do defer to the existing issue, and if you want to work with us on adding such a capability, please let me know!

**Comment by ahuang11** [comment]
Would love to help out in the near future, but not sure how it would be structured /get started. Would all params just inherit a `cli` keyword which activates the CLI?
