### ISSUE TITLE
Documentation has a dirty HTML title

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/param#569]
The documentation is dirty:
![image](https://user-images.githubusercontent.com/19758978/141612841-38bb051c-3a4d-4e1a-9c0f-af25f6637d12.png)

![image](https://user-images.githubusercontent.com/19758978/141612877-52d796e9-be7a-4524-82a8-0583418de9cc.png)

Something similar happened here https://github.com/holoviz/panel/issues/2099

**Comment by maximlt** [comment]
Thanks for reporting that. The site title is obtained from the git describe version, which here is not just 1.12.0 because the site built happened a few commits after the actual param release, I guess there were some docs issues to fix and we then triggered a manual build.

I've been thinking of a way to declare the site version via the Github Actions UI. I'll experiment with that.

And renaming the title here, since it's just the html title that's not clean, not the whole website :)

**Comment by jbednar** [comment]
Right. I rebuilt the docs to fix https://github.com/holoviz/param/issues/567, but it would be great if I could declare that the actual code of the library is still the same as the 1.12.0 tag. In fact, I can't think of any particular reason the public site should _ever_ show anything but the numeric version x.x.x. The dev site could show the full SHA like that, so that we can be sure which build it was, but it seems very unlikely we'd want any public site user to care about the SHA for the build rather than the official version number.
