### ISSUE TITLE
Remove `exceptions_summarized`

### ISSUE THREAD

**Issue by maximlt** [holoviz/param#585]
This context manager is very useful for the documentation but far less for param users themselves. It could actually confuse them (https://discourse.holoviz.org/t/determine-how-a-param-is-being-set-as-readonly/3189/2).

Let's remove it and add it to a `docs_util.py` module that would live next to the notebooks? I quickly tried to find a Python package on PyPi that would offer this context manager but couldn't find one (there are so many packages on PyPi!).

**Comment by jbednar** [comment]
Param can't depend on anything from PyPI; it's intended as a standalone library so that it is always trivial to add it to a user's project.  And the example notebooks are meant to be good reference material for people to cut and paste into their own work, so I wouldn't want to use a utility only available during doc building. 

Illustrating expected exceptions seems important for training material and documentation, but I haven't found any support for that in nbconvert or related tools. What I'd love to see is for nbconvert to respect a cell metadata field where we declare that the cell is expected to raise an exception, so that it can format it appropriately for the docs and avoid aborting the notebook execution. That way a user wouldn't have to deal with things like `exceptions_summarized`, but it would still be fully runnable code while formatting nicely on the website. But that would be painful to try to implement and document in nbconvert, so I'm not likely to attempt it.

If someone wants to edit `exceptions_summarized` to summarize only the param-raised exceptions I'd support that, which would help people spot actual coding errors. But otherwise, I don't see anything to do here that would be an overall net improvement.

**Comment by maximlt** [comment]
Oh no I didn't intend to add any dependency to `param`, I meant to find a library that provides the `exceptions_summarized` utility (which wouldn't have been the only library the docs use since it relies on aiohttp and panel). Unfortunately I couldn't find one, at least in the 5 minutes I've spent searching for it on pypi ;)

Seems like there's a way to tag cells that are expected to raise an error (https://nbconvert.readthedocs.io/en/latest/changelog.html?highlight=exception#changes-in-how-we-handle-metadata) and I remember there's an ipython magic toggle to reduce a traceback. Mixing both might get what you want.

I would still be happy if Param would not ship `exceptions_summarized`, it's the most visible object that Param provides in the docs which is a bit unfair to all the other goodies people should use :D

**Comment by jbednar** [comment]
That metadata support looks very promising! I have a notebook extension that suppresses tracebacks, but I don't know if it works with nbconvert/nbexecute. If it does that could be a very nice solution!
