### ISSUE TITLE
Refactor __init__.py according to modern Python and best practices

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/param#648]
I see some issues with the main `__init__.py` file that makes using Param and contributing to it harder than it has to be.

- The`__init__.py` has grown to +2000 lines. What I normally see as best practice is to say maximum 1000 lines to make the file understandable. And preferably max around 250 lines.
- A `__init__.py` is not meant to contain a lot of the implementation details. A *best practice* `__init__.py` should
  - expose a module docstring which is useful for users
  - import the *public* classes, functions and other objects.
  - define an `__all__` method which guides *wild card imports* (if anyone uses that) and editors like VS Code based on static analysis to the "public" functionality.

My request is a refactoring guided by the best practices above to help users and future contributors.

**Comment by jbednar** [comment]
Defining `__all__` would be useful. One could move the entire contents of `__init__.py` to its own file `parameters.py`, but that would add an additional file, and I'm not sure I see what the benefit would be. Who defines `is not meant to`?

**Comment by philippjfr** [comment]
People generally cite this blog post:

>Leaving an __init__.py file empty is considered normal and even a good practice, if the package’s modules and sub-packages do not need to share any code. [Source](https://python-docs.readthedocs.io/en/latest/writing/structure.html)

and it is the consensus of most Python devs if you survey StackOverflow answers, reddit posts etc. `__init__.py` is really meant to be used for initialization code and declaring imports and defining `__all__`, here's what the Python docs say:

>In the simplest case, __init__.py can just be an empty file, but it can also execute initialization code for the package or set the __all__ variable, described later.

On balance I agree we should refactor param, the file is unwieldy and there's no reason for it really. If param was still small enough to be a single file I'd favor just dropping it all into `__init__.py` but that's not the case so I don't see any reason not to have better organization.

**Comment by maximlt** [comment]
Indeed, because there's a lot of code in `__init__.py` the auto-completion suggests many irrelevant objects like `param.sys` or `param.OrderedDict`. Moving that code to another module would help. Or importing them *as* private objects (`import os as _os`). I'd probably prefer moving the code to another module, since anyway Param is already two files with `__init__.py` and `parameterized.py`, except if you're only interested in the `String` parameter :D

**Comment by jbednar** [comment]
I don't have much feeling for or against splitting the parameter definitions into their own file. If someone wishes to do that, be my guest! It does add an extra file, but yes, the file has gotten quite long for an init file, and splitting it does make it easy to marshal the public bits into the namespace. If it's to happen, it should happen ASAP before we release Param 2.0, because any bits we fail to import into the init file will no longer be public API.

**Comment by maximlt** [comment]
My plan was to do this refactoring once there are a sufficient number of PRs merged, as that will cause a lot of conflicts.
