### ISSUE TITLE
Review the public API

### ISSUE THREAD

**Issue by ceball** [holoviz/param#69]
We've never had the time to go through systematically and review the public API. (Could be done while improving the reference manual.)

**Comment by jlstevens** [comment]
I've gone through the list using ``dir`` on a basic parameterized object together with Philipp and here are our thoughts.  Of course, this is just expressing only our opinions as relatively veteran param users and this is just for reference for whenever a proper clean-up happens. :-)

Here are the things we don't like the look of and never use ourselves:

``set_param``, ``set_default``,  ``print_param_defaults``, ``print_param_values``,  ``initialized``, ``defaults``.

The print ones seem particularly nasty to me, initialized is just a boolean (why doesn't it have an underscore in front of it?).  We see how ``set_param``, ``set_default`` and ``defaults``  might be useful in some cases but couldn't these be functions available in param instead of methods?

There are two more things that we know are useful but are also rarely used:  ``inspect_value``, ``force_new_dynamic_value``. Again, could these things be functions instead?

I would like to see ``script_repr`` renamed to ``pprint``. We understand the need for everything else listed by ``dir`` and have ignored everything introduced with an underscore.

**Comment by jbednar** [comment]
I would be happy to make ``set_param, set_default, print_param_defaults, print_param_values``, and ``defaults`` into separate functions, if they are ever used, or to delete them if they are not, and to change ``initialized`` to ``_initialized``.  

I'm not irritated by ``inspect_value`` and ``force_new_dynamic_value``, but if they can be made into external functions, then sure.

I would be happier with pprint than script_repr.

**Comment by ceball** [comment]
See also:
* #154 
* #8

**Comment by ceball** [comment]
Also see #233

**Comment by jbednar** [comment]
Covered by #233.
